my:
   app:
      pid: 45
      pname: ITC
      pprice: 452
      details:
       -   D1
       -   D2
       -   D3
      versions:
       V1: 2
       V2: 3
       V3: 4
      vob:
        vid: 12
        vname: Jubliant